# -*- coding: utf-8 -*-
"""Credit Card Fraud Detection System .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GViykk7QeWjZBjcxgeLowMKVvaMdvFpI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

import plotly.express as px
import plotly.graph_objects as go

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Python Project/credit_card_fraud_10k.csv")
print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

df = df.drop_duplicates()

print("\nDataset Shape After Removing Duplicates:", df.shape)

print("\nData Types:")
print(df.dtypes)

print("""DESCRIPTIVE STATISTICS""")

print("\nStatistical Summary:")
print(df.describe())

# Average transaction amount
avg_amount = df["amount"].mean()
print("\nAverage Transaction Amount:", avg_amount)

# Fraud vs Normal transaction count
fraud_count = df["is_fraud"].value_counts()

print("\nFraud vs Normal Transactions:")
print(fraud_count)

"""FRAUD BEHAVIOR ANALYSIS"""

normal_transactions = df[df["is_fraud"] == 0]
fraud_transactions = df[df["is_fraud"] == 1]

print("\nNormal Transactions:")
print(normal_transactions.describe())

print("\nFraud Transactions:")
print(fraud_transactions.describe())

"""GROUP BASED ANALYSIS"""

# Average amount by class
group_analysis = df.groupby("is_fraud")["amount"].mean()

print("\nAverage Transaction Amount by Class:")
print(group_analysis)

"""RELATIONSHIP ANALYSIS"""

# Exclude non-numeric columns before calculating correlation
correlation = df.drop(columns=['merchant_category']).corr()

"""DATA VISUALIZATION"""

sns.set_style("whitegrid")

"""Fraud Distribution"""

plt.figure(figsize=(6,4))
sns.countplot(x='is_fraud', data=df)
plt.title("Fraud vs Normal Transactions")
plt.xlabel("Class (0 = Normal, 1 = Fraud)")
plt.ylabel("Count")
plt.show()

"""Transaction Amount Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df['amount'], bins=50, kde=True)
plt.title("Transaction Amount Distribution")
plt.xlabel("Amount")
plt.show()

"""Scatter Plot"""

plt.figure(figsize=(8,5))
sns.scatterplot(x='transaction_hour', y='amount', hue='is_fraud', data=df)
plt.title("Transaction Hour vs Amount")
plt.show()

"""Box Plot"""

plt.figure(figsize=(6,4))
sns.boxplot(x='is_fraud', y='amount', data=df)
plt.title("Amount vs Fraud")
plt.show()

"""Correlation Heatmap"""

plt.figure(figsize=(14,10))
sns.heatmap(correlation, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Risk Analysis

def risk_level(amount):
    if amount < 100:
        return "Low Risk"
    elif amount < 1000:
        return "Medium Risk"
    else:
        return "High Risk"

df["Risk_Level"] = df["amount"].apply(risk_level)

print("\nRisk Level Distribution:")
print(df["Risk_Level"].value_counts())

# LINEAR REGRESSION MODEL

# Independent Variables
X = df[['transaction_hour']]

# Dependent Variable
y = df['amount']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create Model
model = LinearRegression()

# Train Model
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

"""MODEL EVALUATION"""

r2 = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("\nModel Evaluation")
print("R2 Score:", r2)
print("Mean Squared Error:", mse)

"""RESIDUAL ANALYSIS"""

residuals = y_test - y_pred

plt.figure(figsize=(8,5))
sns.histplot(residuals, bins=50, kde=True)
plt.title("Residual Distribution")
plt.xlabel("Residuals")
plt.show()

"""INTERACTIVE DASHBOARD"""

# Fraud Distribution Chart
fig1 = px.histogram(
    df,
    x="is_fraud",
    title="Fraud vs Normal Transactions",
    labels={"is_fraud": "Transaction Type"}
)

fig1.show()

# Transaction Amount Trend
fig2 = px.scatter(
    df,
    x="transaction_hour",
    y="amount",
    color="is_fraud",
    title="Transaction Amount Over Time"
)
fig2.show()

# Risk Level Chart
fig3 = px.pie(
    df,
    names="Risk_Level",
    title="Risk Level Distribution"
)

fig3.show()

# Correlation Heatmap
fig4 = go.Figure(
    data=go.Heatmap(
        z=correlation.values,
        x=correlation.columns,
        y=correlation.columns,
        colorscale='Viridis'
    )
)

""" INSIGHTS & CONCLUSION"""

print("\nPROJECT INSIGHTS")
print("---------------------------")
print("1. Fraud transactions are very low compared to normal transactions.")
print("2. Transaction amount plays an important role in fraud detection.")
print("3. Some features show strong correlations with fraudulent activity.")
print("4. High-risk transactions can be identified using amount patterns.")
print("5. Dashboard visualizations help understand fraud behavior easily.")

print("\nThis Project Was Completed Successfully.")